### ISSUE TITLE
[FR]请支持其他方式登录，例如邮箱、手机等+密码的形式

### ISSUE THREAD

**Issue by YClinks** [thx/iconfont-plus#2055]
请支持其他方式登录，例如邮箱、手机等+密码的形式

**Comment by yisibl** [comment]
感谢建议 我们自己在全力开发了，近期会上线手机注册登录



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月8日(周日) 上午10:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] [FR]请支持其他方式登录，例如邮箱、手机等+密码的形式 (#2055)




 
请支持其他方式登录，例如邮箱、手机等+密码的形式
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
