### ISSUE TITLE
上传svg失败 / 插画如何加入项目

### ISSUE THREAD

**Issue by havenothingtosay** [thx/iconfont-plus#2078]
## 问题描述
想上传一个图片作为iconfont加入到自己的项目里，但是上传图标svg会报错，上传插画svg成功但是插画无法加入项目（如果是我未找到加入项目的操作路径，麻烦告知一下也可以，谢谢！）。
## 相关截图
![image](https://user-images.githubusercontent.com/19619291/132179334-79a37bd4-826b-4926-98d8-ba1ee5a6da4d.png)
![image](https://user-images.githubusercontent.com/19619291/132179412-9d4b2a31-c984-406c-857c-9e17b7aa5512.png)

**Comment by yisibl** [comment]
请提供SVG文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月6日(周一) 下午3:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] 想上传一个图片作为iconfont加入到自己的项目里 (#2078)




 
问题描述
 
想上传一个图片作为iconfont加入到自己的项目里，但是上传图标svg会报错，上传插画svg成功但是插画无法加入项目（如果是我未找到加入项目的操作路径，麻烦告知一下也可以，谢谢！）。
 
相关截图
 

 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by havenothingtosay** [comment]
这里不能直接上传svg文件，麻烦到[这个网址](https://iconscout.com/icon/microsoft-dot-net-1#)里下载svg图片吧

**Comment by yisibl** [comment]
不支持渐变

**Comment by havenothingtosay** [comment]
好的，了解了，谢谢！

**Comment by 2016604782** [comment]
![Xnip2022-04-13_18-43-17](https://user-images.githubusercontent.com/88182478/163164563-e0aae36f-d59b-415f-925b-976636ef4a77.jpg)
你好,我的插画矢量图标上传一直显示加载中,尺寸按照官方1024px建的画板,但是一直上传不了

**Comment by yisibl** [comment]
@2016604782 请提供 SVG 文件

**Comment by 2016604782** [comment]
![暂无通知](https://user-images.githubusercontent.com/88182478/163183441-54dce61b-a081-403e-b2a1-65b4a5d8ad3a.svg)
这个

**Comment by 2016604782** [comment]
> @2016604782请提供SVG文件
![暂无通知](https://user-images.githubusercontent.com/88182478/163183511-60337d30-8f71-4b42-a265-0693a5bd6653.svg)

**Comment by 2016604782** [comment]
@yisibl 就是上面这个svg文件,刚刚试过上传也是一直显示加载
![Xnip2022-04-14_10-03-15](https://user-images.githubusercontent.com/88182478/163299418-38f8e3e9-a292-4f61-bb57-3199bd956703.jpg)
中

**Comment by yisibl** [comment]
@2016604782 我们看一下

**Comment by 2016604782** [comment]
> @2016604782我们看一下

好的,谢谢,希望能解决
因为试过更大的尺寸,图标也是居中,也是svg格式,上传也是一直显示加载中

**Comment by yisibl** [comment]
@2016604782 已经修复，请再试一下。

**Comment by 2016604782** [comment]
> @2016604782 已经修复，请再试一下。

可以啦,辛苦了,谢谢♥️
