### ISSUE TITLE
官网图标加载失败

### ISSUE THREAD

**Issue by Moyoung-Li** [thx/iconfont-plus#2397]
![image](https://user-images.githubusercontent.com/37606111/197710549-f8c83245-aba6-47b2-b02b-331766fbab70.png)

**Comment by onlymarryu** [comment]
解决了吗

**Comment by Moyoung-Li** [comment]
没有，你自己打开官网查看就知道了：https://www.iconfont.cn/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 晚上6:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





 
解决了吗

**Comment by yisibl** [comment]
可能是网速的问题，图标还没加载。

**Comment by Moyoung-Li** [comment]
不是网速问题，官方已经解决啦，也发了公告




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





 
可能是网速的问题，图标还没加载。

**Comment by Moyoung-Li** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





 
可能是网速的问题，图标还没加载。

**Comment by onlymarryu** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "thx/iconfont-plus" ***@***.***&gt;; 发送时间:&nbsp;2022年11月24日(星期四) 下午4:36 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "thx/iconfont-plus" ***@***.***&gt;; 发送时间:&nbsp;2022年11月24日(星期四) 下午4:36 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


那你项目中替换了吗。这还是没有小方块

**Comment by Moyoung-Li** [comment]
我项目一直没有问题，我提交的问题是官方网站自己本身显示的小方块，官方已经解决了，他官网正常显示了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





  
------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "thx/iconfont-plus" @.&gt;; 发送时间:&nbsp;2022年11月24日(星期四) 下午4:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
   
------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "thx/iconfont-plus" @.&gt;; 发送时间:&nbsp;2022年11月24日(星期四) 下午4:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
那你项目中替换了吗。这还是没有小方块

**Comment by onlymarryu** [comment]
能把你的配置文件发我一份吗




ideality～
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





 我项目一直没有问题，我提交的问题是官方网站自己本身显示的小方块，官方已经解决了，他官网正常显示了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年11月24日(星期四) 下午4:41 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 
 
 
 
 
 
    
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;gt;; 发送时间:&amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;gt;; @.@.&amp;gt;; 主题:&amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;gt; 
     
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;gt;; 发送时间:&amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;gt;; @.@.&amp;gt;; 主题:&amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;gt; 
    
 那你项目中替换了吗。这还是没有小方块

**Comment by Moyoung-Li** [comment]
你理解错啦，不是我项目问题啊，是官网自己的问题，我上面提交的截图是官网首页的截图




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





 能把你的配置文件发我一份吗 
 
 
 
 
 ideality～ 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年11月24日(星期四) 下午4:47 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 
 
 
 
 
 
  我项目一直没有问题，我提交的问题是官方网站自己本身显示的小方块，官方已经解决了，他官网正常显示了  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年11月24日(星期四) 下午4:41  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)  
   
   
   
   
   
      
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;amp;gt;; @.@.&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;amp;gt;  
       
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;amp;gt;; @.@.&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;amp;gt;  
      
  那你项目中替换了吗。这还是没有小方块

**Comment by onlymarryu** [comment]
没有理解错，你的是对的嘛，我就想着参考着看一下我的文件是不是那写错了




ideality～
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





 你理解错啦，不是我项目问题啊，是官网自己的问题，我上面提交的截图是官网首页的截图 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年11月24日(星期四) 下午4:48 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 
 
 
 
 
 
  能把你的配置文件发我一份吗  
   
   
   
   
  ideality～  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年11月24日(星期四) 下午4:47  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)  
   
   
   
   
   
   我项目一直没有问题，我提交的问题是官方网站自己本身显示的小方块，官方已经解决了，他官网正常显示了   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2022年11月24日(星期四) 下午4:41   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)   
     
     
     
     
     
        
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;amp;amp;gt;; 发送时间:&amp;amp;amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;amp;amp;gt;; @.@.&amp;amp;amp;gt;; 主题:&amp;amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;amp;amp;gt;   
         
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;amp;amp;gt;; 发送时间:&amp;amp;amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;amp;amp;gt;; @.@.&amp;amp;amp;gt;; 主题:&amp;amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;amp;amp;gt;   
        
   那你项目中替换了吗。这还是没有小方块

**Comment by Moyoung-Li** [comment]
你前端使用什么框架？你在官网搜索你想要的图标，加入购物车，然后添加到项目，没有项目，创建项目，把你所有需要的图标都添加到这个项目里面，然后把代码下载下来，放到你自己的项目里面去，全局引入，就可以使用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)





 没有理解错，你的是对的嘛，我就想着参考着看一下我的文件是不是那写错了 
 
 
 
 
 ideality～ 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年11月24日(星期四) 下午4:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 
 
 
 
 
 
  你理解错啦，不是我项目问题啊，是官网自己的问题，我上面提交的截图是官网首页的截图  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年11月24日(星期四) 下午4:48  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)  
   
   
   
   
   
   能把你的配置文件发我一份吗   
     
     
     
     
   ideality～   
   ***@***.***   
     
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2022年11月24日(星期四) 下午4:47   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)   
     
     
     
     
     
    我项目一直没有问题，我提交的问题是官方网站自己本身显示的小方块，官方已经解决了，他官网正常显示了    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2022年11月24日(星期四) 下午4:41    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397)    
       
       
       
       
       
          
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;amp;amp;amp;gt;; 发送时间:&amp;amp;amp;amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;amp;amp;amp;gt;; @.@.&amp;amp;amp;amp;gt;; 主题:&amp;amp;amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;amp;amp;amp;gt;    
           
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------ 发件人: "thx/iconfont-plus" @.&amp;amp;amp;amp;gt;; 发送时间:&amp;amp;amp;amp;nbsp;2022年11月24日(星期四) 下午4:36 @.&amp;amp;amp;amp;gt;; @.@.&amp;amp;amp;amp;gt;; 主题:&amp;amp;amp;amp;nbsp;Re: [thx/iconfont-plus] 官网图标加载失败 (Issue #2397) 可能是网速的问题，图标还没加载。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;amp;amp;amp;gt;    
          
    那你项目中替换了吗。这还是没有小方块
